log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    # http
    address: ":8000"
    # http:
    #   redirections:
    #     entryPoint:
    #       to: web-secure

  web-secure:
    # https
    address: ":443"

  # flower:
  #   address: ":5555"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "{{cookiecutter.email}}"
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web


providers:
  # https://docs.traefik.io/master/providers/file/
  # file:
  #   filename: /etc/traefik/traefik.yml
  #   watch: true
  file:
    directory: /etc/traefik
    watch: true
  docker:
      endpoint: "unix:///var/run/docker.sock"
      exposedByDefault: false
