log:
  level: INFO

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    # http
    address: ":80"
    # http:
    #   redirections:
    #     entryPoint:
    #       to: web-secure

  web-secure:
    # https
    address: ":443"

  # flower:
  #   address: ":5555"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "{{ cookiecutter.email }}"
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-router:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      middlewares:
      # reachable at port 80, no redirect
      #  - redirect
        - csrf
      service: django


  middlewares:
    #redirect:
      # https://docs.traefik.io/master/middlewares/redirectscheme/
      #redirectScheme:
      #  scheme: https
      #  permanent: true
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

#     # flower:
#     #   loadBalancer:
#     #     servers:
#     #       - url: http://flower:5555

providers:
  # https://docs.traefik.io/master/providers/file/
  # file:
  #   filename: /etc/traefik/traefik.yml
  #   watch: true
  file:
    directory: /etc/traefik
    watch: true
  # docker:
  #     endpoint: "unix:///var/run/docker.sock"
  #     exposedByDefault: false
